/*  postgres - Base Module: Create Domain std_foreign_name to denote a name not generated by the host databae. - ddl  */

-- drop domain chief.std_foreign_name;
create domain chief.std_foreign_name
    as text
;

comment on domain chief.std_foreign_name is 'Name not generated by the host database. Typically a name from an external system such as a client''s database.';

