/*  postgres - Base Module: Create Domain std_foreign_ident to denote an identifier not generated by the host databae. - ddl  */

-- drop domain chief.std_foreign_ident;
create domain chief.std_foreign_ident
    as text
;

comment on domain chief.std_foreign_ident is 'Identifier not generated by the host database. Typically an ID from an external system such as a client''s database.';
