/*  postgres - Base Module: Create Domain std_name, a name generated by the host database. - ddl  */

-- drop domain chief.std_name;
create domain chief.std_name
    as text
;

comment on domain chief.std_name is 'Name generated by the host database.';
