/*  postgres - Base Module: Create Domain std_id, a UUID for foreign and primary key values. - ddl  */

-- drop domain chief.std_id;
create domain chief.std_id
    as uuid
;

comment on domain chief.std_id is 'UUID Identifier generated by gen_random_uuid(), typically for Foreign Keys and Primary Keys.';
