/*  postgres - Base Module: Create Domain std_pk, a UUID primary key generated by a table definition. - ddl  */

-- drop domain chief.std_pk;
create domain chief.std_pk
    as chief.std_id
    not null
    default gen_random_uuid() 
;

comment on domain chief.std_pk is 'Primary Key generated by a table definition. Uses domain: chief.std_id.';
