/*  postgres - Base Module: Create Domain std_abbr, an abbreviation generated by the host database. - ddl  */

-- drop domain chief.std_abbr;
create domain chief.std_abbr
    as varchar(64)
    not null
;

comment on domain chief.std_abbr is 'Abbreviation generated by the host database.';
